export interface Product {
  id: string;
  title: string;
  titleZh?: string;
  titleTh?: string;
  price: number;
  negotiable: boolean;
  condition: 'new' | 'ninetyNew' | 'eightyNew' | 'repairable';
  campus: 'mainCampus' | 'secondaryCampus' | 'offCampus';
  category: 'books' | 'electronics' | 'dormFurniture' | 'sports' | 'clothing' | 'tickets' | 'others';
  image: string;
  images?: string[];
  description?: string;
  descriptionZh?: string;
  descriptionTh?: string;
  specifications?: Record<string, string>;
  seller: {
    name: string;
    avatar: string;
    role: 'student' | 'staff';
    verified: boolean;
    rating: number;
    totalTrades?: number;
    responseTime?: string;
    joinDate?: string;
  };
  deliveryType: ('faceToFace' | 'campusLocker' | 'courier')[];
  badges: ('includesReceipt' | 'inWarranty' | 'pickupOnly')[];
  views: number;
  publishedDate: string;
  distance?: string;
  itemLanguage: 'chinese' | 'english' | 'thai';
  avgMarketPrice?: number;
  lowestRecentPrice?: number;
  brand?: string;
  courseCode?: string;
  sold?: boolean;
}

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'MacBook Pro 2021 M1 Pro 14" - Excellent Condition',
    titleZh: 'MacBook Pro 2021 M1 Pro 14寸 - 成色极好',
    titleTh: 'MacBook Pro 2021 M1 Pro 14" - สภาพดีมาก',
    price: 1200,
    negotiable: true,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1602454252462-3fe9e21cc149?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWNib29rJTIwcHJvJTIwbGFwdG9wfGVufDF8fHx8MTc2MTAzMTU4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1602454252462-3fe9e21cc149?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWNib29rJTIwcHJvJTIwbGFwdG9wfGVufDF8fHx8MTc2MTAzMTU4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxtYWNib29rJTIwcHJvJTIwbGFwdG9wfGVufDF8fHx8MTc2MTAzMTU4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxtYWNib29rJTIwcHJvJTIwbGFwdG9wfGVufDF8fHx8MTc2MTAzMTU4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    description: 'MacBook Pro 2021 with M1 Pro chip, 14-inch display. Perfect for students and professionals. Used mainly for coursework and light video editing. Battery health still at 95%. Comes with original charger and box. No scratches or dents, always kept in a protective case.',
    descriptionZh: 'MacBook Pro 2021，配备M1 Pro芯片，14英寸显示屏。主要用于课程作业和轻度视频编辑。电池健康度仍为95%。附带原装充电器和包装盒。无划痕或凹痕，一直使用保护壳。',
    descriptionTh: 'MacBook Pro 2021 พร้อมชิป M1 Pro หน้าจอ 14 นิ้ว ใช้งานหลักสำหรับงานเรียนและตัดต่อวิดีโอเบาๆ แบตเตอรี่ยังมีสุขภาพ 95% มาพร้อมกับที่ชาร์จและกล่องของแท้',
    specifications: {
      'Model': 'MacBook Pro 14" 2021',
      'Processor': 'Apple M1 Pro',
      'RAM': '16GB',
      'Storage': '512GB SSD',
      'Warranty': 'Until May 2026',
    },
    seller: {
      name: 'Sarah Chen',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.8,
      totalTrades: 24,
      responseTime: '1 hour',
      joinDate: 'Aug 2023',
    },
    deliveryType: ['faceToFace', 'campusLocker'],
    badges: ['includesReceipt', 'inWarranty'],
    views: 234,
    publishedDate: '2025-10-19',
    distance: '0.5 km',
    itemLanguage: 'english',
    avgMarketPrice: 1350,
    lowestRecentPrice: 1100,
    brand: 'Apple',
  },
  {
    id: '2',
    title: 'Introduction to Algorithms (4th Edition) - Like New',
    titleZh: '算法导论（第4版）- 几乎全新',
    titleTh: 'Introduction to Algorithms (ฉบับที่ 4) - เหมือนใหม่',
    price: 45,
    negotiable: false,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1634194477662-b1c0b5dfe65d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZXh0Ym9vayUyMGFsZ29yaXRobXN8ZW58MXx8fHwxNzYxMDMxNTg2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Michael Wang',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.9,
    },
    deliveryType: ['faceToFace'],
    badges: ['includesReceipt'],
    views: 89,
    publishedDate: '2025-10-20',
    distance: '1.2 km',
    itemLanguage: 'english',
    avgMarketPrice: 55,
    lowestRecentPrice: 40,
    courseCode: 'CS301',
  },
  {
    id: '3',
    title: 'Mini Fridge - Perfect for Dorm Room',
    titleZh: '迷你冰箱 - 宿舍专用',
    titleTh: 'ตู้เย็นขนาดเล็ก - เหมาะสำหรับหอพัก',
    price: 80,
    negotiable: true,
    condition: 'eightyNew',
    campus: 'secondaryCampus',
    category: 'dormFurniture',
    image: 'https://images.unsplash.com/photo-1643494847705-74808059bf07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pJTIwcmVmcmlnZXJhdG9yfGVufDF8fHx8MTc2MTAzMTU4N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Lisa Thompson',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.5,
    },
    deliveryType: ['faceToFace'],
    badges: ['pickupOnly'],
    views: 156,
    publishedDate: '2025-10-18',
    distance: '3.5 km',
    itemLanguage: 'english',
    avgMarketPrice: 100,
    lowestRecentPrice: 75,
  },
  {
    id: '4',
    title: 'iPad Air 2022 with Apple Pencil',
    titleZh: 'iPad Air 2022 配 Apple Pencil',
    titleTh: 'iPad Air 2022 พร้อม Apple Pencil',
    price: 450,
    negotiable: true,
    condition: 'new',
    campus: 'mainCampus',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1672298597883-aba600a9b5a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpcGFkJTIwdGFibGV0fGVufDF8fHx8MTc2MTAzMTU4N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Dr. James Kim',
      avatar: '',
      role: 'staff',
      verified: true,
      rating: 5.0,
    },
    deliveryType: ['faceToFace', 'courier'],
    badges: ['includesReceipt', 'inWarranty'],
    views: 312,
    publishedDate: '2025-10-21',
    distance: '0.8 km',
    itemLanguage: 'english',
    avgMarketPrice: 500,
    lowestRecentPrice: 440,
    brand: 'Apple',
  },
  {
    id: '5',
    title: 'Basketball - Wilson Evolution',
    titleZh: '篮球 - Wilson Evolution',
    titleTh: 'บาสเกตบอล - Wilson Evolution',
    price: 25,
    negotiable: false,
    condition: 'eightyNew',
    campus: 'mainCampus',
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1607629002307-1d4b59e23e75?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXNrZXRiYWxsJTIwc3BvcnRzfGVufDF8fHx8MTc2MDk2MjQwN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Alex Rivera',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.7,
    },
    deliveryType: ['faceToFace'],
    badges: [],
    views: 67,
    publishedDate: '2025-10-17',
    distance: '1.0 km',
    itemLanguage: 'english',
    brand: 'Wilson',
  },
  {
    id: '6',
    title: 'Concert Tickets - Rock Band Live (2 tickets)',
    titleZh: '演唱会门票 - 摇滚乐队现场（2张）',
    titleTh: 'ตั๋วคอนเสิร์ต - Rock Band Live (2 ใบ)',
    price: 60,
    negotiable: true,
    condition: 'new',
    campus: 'offCampus',
    category: 'tickets',
    image: 'https://images.unsplash.com/photo-1515139372923-c923c9e9a18c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25jZXJ0JTIwdGlja2V0c3xlbnwxfHx8fDE3NjEwMzE1ODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Emma Johnson',
      avatar: '',
      role: 'student',
      verified: false,
      rating: 4.2,
    },
    deliveryType: ['faceToFace', 'courier'],
    badges: [],
    views: 201,
    publishedDate: '2025-10-16',
    itemLanguage: 'english',
  },
  {
    id: '7',
    title: 'Study Desk with Chair - Ikea',
    titleZh: '学习桌配椅子 - 宜家',
    titleTh: 'โต๊ะเรียนพร้อมเก้าอี้ - Ikea',
    price: 65,
    negotiable: true,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'dormFurniture',
    image: 'https://images.unsplash.com/photo-1585832770485-e68a5dbfad52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHVkeSUyMGRlc2t8ZW58MXx8fHwxNzYxMDMxNTg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Ryan Park',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.6,
    },
    deliveryType: ['faceToFace'],
    badges: ['pickupOnly'],
    views: 134,
    publishedDate: '2025-10-15',
    distance: '2.1 km',
    itemLanguage: 'english',
    avgMarketPrice: 80,
    lowestRecentPrice: 60,
    brand: 'Ikea',
  },
  {
    id: '8',
    title: 'Calculus Textbook - Early Transcendentals',
    titleZh: '微积分教材 - 早期超越',
    titleTh: 'หนังสือแคลคูลัส - Early Transcendentals',
    price: 35,
    negotiable: true,
    condition: 'eightyNew',
    campus: 'secondaryCampus',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1646495785840-7ff6be438d63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWxjdWx1cyUyMHRleHRib29rfGVufDF8fHx8MTc2MTAzMTU4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Sophie Martinez',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.8,
    },
    deliveryType: ['faceToFace', 'campusLocker'],
    badges: [],
    views: 98,
    publishedDate: '2025-10-14',
    distance: '4.0 km',
    itemLanguage: 'english',
    courseCode: 'MATH201',
  },
  {
    id: '9',
    title: 'North Face Jacket - Medium Size',
    titleZh: 'North Face 夹克 - 中号',
    titleTh: 'แจ็คเก็ต North Face - ไซส์ M',
    price: 75,
    negotiable: false,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'clothing',
    image: 'https://images.unsplash.com/photo-1706765779494-2705542ebe74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aW50ZXIlMjBqYWNrZXR8ZW58MXx8fHwxNzYxMDMwNjcwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'David Lee',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.9,
    },
    deliveryType: ['faceToFace', 'courier'],
    badges: ['includesReceipt'],
    views: 178,
    publishedDate: '2025-10-13',
    distance: '1.5 km',
    itemLanguage: 'english',
    brand: 'The North Face',
  },
  {
    id: '10',
    title: 'Gaming Mouse - Logitech G502',
    titleZh: '游戏鼠标 - 罗技 G502',
    titleTh: 'เมาส์เกมมิ่ง - Logitech G502',
    price: 40,
    negotiable: true,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1628832307345-7404b47f1751?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBtb3VzZXxlbnwxfHx8fDE3NjA5Mzk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Chris Anderson',
      avatar: '',
      role: 'student',
      verified: true,
      rating: 4.7,
    },
    deliveryType: ['faceToFace', 'campusLocker'],
    badges: ['includesReceipt'],
    views: 145,
    publishedDate: '2025-10-12',
    distance: '0.7 km',
    itemLanguage: 'english',
    brand: 'Logitech',
  },
  {
    id: '11',
    title: 'Yoga Mat with Carrying Bag',
    titleZh: '瑜伽垫配收纳袋',
    titleTh: 'เสื่อโยคะพร้อมกระเป๋า',
    price: 20,
    negotiable: false,
    condition: 'eightyNew',
    campus: 'secondaryCampus',
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1646239646963-b0b9be56d6b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2dhJTIwbWF0fGVufDF8fHx8MTc2MTAzMTU4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Jessica Brown',
      avatar: '',
      role: 'student',
      verified: false,
      rating: 4.3,
    },
    deliveryType: ['faceToFace'],
    badges: [],
    views: 92,
    publishedDate: '2025-10-11',
    distance: '3.2 km',
    itemLanguage: 'english',
  },
  {
    id: '12',
    title: 'Dell Monitor 24" Full HD',
    titleZh: 'Dell 显示器 24寸 全高清',
    titleTh: 'จอคอมพิวเตอร์ Dell 24" Full HD',
    price: 120,
    negotiable: true,
    condition: 'ninetyNew',
    campus: 'mainCampus',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1611648694931-1aeda329f9da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21wdXRlciUyMG1vbml0b3J8ZW58MXx8fHwxNzYwOTcwNDQwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    seller: {
      name: 'Prof. Zhang Wei',
      avatar: '',
      role: 'staff',
      verified: true,
      rating: 5.0,
    },
    deliveryType: ['faceToFace'],
    badges: ['includesReceipt', 'inWarranty'],
    views: 267,
    publishedDate: '2025-10-10',
    distance: '1.8 km',
    itemLanguage: 'english',
    avgMarketPrice: 150,
    lowestRecentPrice: 110,
    brand: 'Dell',
    sold: false,
  },
];
